/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_App */

#ifndef _Included_com_example_App
#define _Included_com_example_App
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_App
 * Method:    call
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_App_call
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
