name: Build and Publish

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: |
          mkdir -p build
          cd build
          cmake ../
          cmake --build . --config Release
      - run: |
          mkdir -p ./src/main/resources/native/
          cp ./build/libapp.so ./src/main/resources/native/
      - uses: actions/setup-java@v5
        with:
          java-version: 8
          distribution: temurin
      - run: mvn test
      - uses: actions/upload-artifact@v7
        with:
          path: ./build/libapp.so
          name: 'libapp.so'
          archive: 'false'
          if-no-files-found: 'error'

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v7
      - run: |
          mkdir -p build
          cd build
          cmake ../
          cmake --build . --config Release
      - run: |
          mkdir -p ./src/main/resources/native/
          cp ./build/Release/app.dll ./src/main/resources/native/
      - uses: actions/setup-java@v5
        with:
          java-version: 8
          distribution: temurin
      - run: mvn test
      - uses: actions/upload-artifact@v7
        with:
          path: ./build/Release/app.dll
          name: 'app.dll'
          archive: 'false'
          if-no-files-found: 'error'

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v7
      - run: |
          mkdir -p build
          cd build
          cmake ../
          cmake --build . --config Release
      - run: |
          mkdir -p ./src/main/resources/native/
          cp ./build/libapp.dylib ./src/main/resources/native/
      - uses: actions/setup-java@v5
        with:
          java-version: 8
          distribution: zulu
      - run: mvn test
      - uses: actions/upload-artifact@v7
        with:
          path: ./build/libapp.dylib
          name: 'libapp.dylib'
          archive: 'false'
          if-no-files-found: 'error'

  build-publish:
    needs: [build-macos, build-ubuntu, build-windows]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-java@v5
        with:
          java-version: 8
          distribution: temurin
      - run: |
          mkdir -p ./src/main/resources/native/
      - uses: actions/download-artifact@v8
        with:
          path: ./src/main/resources/native/
          name: 'libapp.so'
      - uses: actions/download-artifact@v8
        with:
          path: ./src/main/resources/native/
          name: 'app.dll'
      - uses: actions/download-artifact@v8
        with:
          path: ./src/main/resources/native/
          name: 'libapp.dylib'
      - run: mvn package
      - uses: actions/upload-artifact@v7
        with:
          path: ./target/app.jar
          name: 'app.jar'
          archive: 'false'
          if-no-files-found: 'error'