name: Build and Publish

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: |
          mkdir -p build
          cd build
          cmake ../
          cmake --build . --config Release
      - uses: actions/setup-java@v5
        if: success()
        with:
          java-version: 8
          distribution: temurin
      - run: |
          cp ./build/libapp.so ./libapp.so
          mvn test
        if: success()
      - uses: actions/upload-artifact@v7
        if: success()
        with:
          path: ./libapp.so
          name: 'libapp.so'
          archive: 'false'
          if-no-files-found: 'error'

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v7
      - run: |
          mkdir -p build
          cd build
          cmake ../
          cmake --build . --config Release
      - uses: actions/setup-java@v5
        if: success()
        with:
          java-version: 8
          distribution: temurin
      - run: |
          cp ./build/Release/app.dll ./app.dll
          mvn test
        if: success()
      - uses: actions/upload-artifact@v7
        if: success()
        with:
          path: ./app.dll
          name: 'app.dll'
          archive: 'false'
          if-no-files-found: 'error'

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v7
      - run: |
          mkdir -p build
          cd build
          cmake ../
          cmake --build . --config Release
      - uses: actions/setup-java@v5
        if: success()
        with:
          java-version: 8
          distribution: zulu
      - run: |
          cp ./build/libapp.dylib ./libapp.dylib
          mvn test
        if: success()
      - uses: actions/upload-artifact@v7
        if: success()
        with:
          path: ./libapp.dylib
          name: 'libapp.dylib'
          archive: 'false'
          if-no-files-found: 'error'

  build-publish:
    needs: [build-macos, build-ubuntu, build-windows]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
